on:
  - deployment
  - deployment_status
  - issue_comment
  - issues
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.BOT_TOKEN }}'
          chat_id: '${{ secrets.CHAT_ID }}'
