on:
  push:
    branches: [ "main" ]
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, deleted]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.BOT_TOKEN }}'
          chat_id: '${{ secrets.CHAT_ID }}'
